### ISSUE TITLE
Sending an email fails: error executing an action: spawn ENOENT

### ISSUE THREAD

**Issue by leonklb** [pimatic/pimatic-mail#1]
When I setup an email rule in pimatic, like the one shown in the example. I get the following error:
'error executing an action: spawn ENOENT' at the moment an email had to be sent. 

I am using:
pimatic version 0.8.66
"pimatic-mail" (0.8.3)
nodemailer 1.3.4
Linux raspberrypi 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l GNU/Linux

Am I missing a dependency?

**Comment by sweetpi** [comment]
Could you post your mail-config (without passwords)?

**Comment by leonklb** [comment]
Thanks for the pointer, my config.json was overwritten. It only contained “plugin”:”mail”. I recreated the config according to the example and it works.  
It would be really nice to improve the logging in case something is wrong with the config.

**Comment by sweetpi** [comment]
The config properties get checked and you should get errors/warnings in the log. Maybe you edited the config while pimatic was running?
