### ISSUE TITLE
Attachment not complete

### ISSUE THREAD

**Issue by moelze** [pimatic/pimatic-mail#9]
I am trying to use a rule to send an email including an attached image. I receive the image at the target email address, however it is only 1kb and cannot be opened. 

Rule: send mail to:"address" subject:"topic" text:"some text" file:"/home/pi/webcam/image.jpg"

At the moment I can't any send any email with an attachment due to error: ECONNRESET
I assume the connection gets closed before the attachment has been transferred.

**Comment by mwittig** [comment]
Sorry for the late reply. I assume this issue is obsolete now, at least I could not reproduce the error in my test setup. Please re-open if you wish to follow up.
